"""Page-specific editorial corrections; product source data is never modified."""
from bs4 import BeautifulSoup

NOTES={
'doner-rekor-arizasi-nasil-anlasilir':('Döner rekor arızası nasıl anlaşılır?','Damlama, dönüş sertliği ve basınç dalgalanmasını ayırın. Döner rekor, hortum ve pompa kaynaklı belirtiler için güvenli ön kontrol rehberi.','Bakım ve arıza'),
'en-iyi-oto-yikama-pervanesi-nasil-secilir':('Oto yıkama pervanesi seçerken neye bakılır?','Doğru pervane; araç tipi, hortum sayısı, montaj altyapısı ve bağlantı uyumuna göre seçilir. Satın alma öncesi kontrol edilecek beş başlık.','Seçim ve bütçe'),
'oto-yikama-boom-pervane-olculeri-yerlesim-plani':('Boom pervane ölçüleri ve yerleşim planı','Kol uzunluğu tek başına yeterli değildir. Kabin ölçüleri, montaj yüksekliği, hortum erişimi ve çevredeki engelleri birlikte değerlendirin.','Kurulum ve uyum'),
'oto-yikama-pervanesi-bakimi':('Oto yıkama pervanesi bakım planı','Görsel kontrol, temizlik, bağlantılar ve kış hazırlığı. Pervane bakımını modelin üretici talimatı ve kullanım yoğunluğuna göre planlayın.','Bakım ve arıza'),
'oto-yikama-pervanesi-balans-ayari':('Pervanede titreşim ve balans kontrolü','Her titreşim balans sorunu değildir. Hortum yükü, montaj hizası ve mekanik boşluğu ayırarak teknik servise doğru bilgi hazırlayın.','Bakım ve arıza'),
'oto-yikama-pervanesi-basinc-hortum-uyumu':('Basınç, hortum ve döner rekor uyumu','Pompa, hortum, rekor ve tabancanın teknik değerlerini birlikte kontrol edin. Basınç kaybı, burulma ve bağlantı uyumsuzluğu için kontrol listesi.','Kurulum ve uyum'),
'oto-yikama-pervanesi-boom-nedir':('Tekli ve çiftli boom pervane arasındaki fark','Tekli boom bir hortum taşır; çiftli boom köpük ve su için iki ayrı hattı yönlendirir. Modellerin kullanım ve montaj farklarını öğrenin.','Seçim ve bütçe'),
'oto-yikama-pervanesi-donmuyor':('Oto yıkama pervanesi neden dönmüyor?','Hiç dönmeyen, belirli açıda takılan veya ağır dönen pervanede önce güvenliği sağlayın. Hortum, bağlantı ve rekor için ön kontrol adımları.','Bakım ve arıza'),
'oto-yikama-pervanesi-fiyatlari':('Oto yıkama pervanesi fiyatı nasıl belirlenir?','Tekli, çiftli ve tır pervanesi teklifinde model, adet, bağlantı parçaları ve sevkiyat kapsamı belirleyicidir. Aynı kapsamlı teklifleri karşılaştırın.','Seçim ve bütçe'),
'oto-yikama-pervanesi-kisin-donma-sorunu':('Oto yıkama pervanesinde donma sorunu','Donma şüphesinde pervaneyi zorlamayın ve hatta basınç vermeyin. Güvenli durdurma, teknik kontrol ve kış hazırlığı için temel rehber.','Bakım ve arıza'),
'oto-yikama-pervanesi-mil-boslugu-olcumu':('Pervane mil boşluğu nasıl kontrol edilir?','Elle hissedilen boşluk bir ön belirtidir; kabul sınırı değildir. Ölçüm, üretici toleransı ve servis değerlendirmesini birbirinden ayırın.','Bakım ve arıza'),
'oto-yikama-pervanesi-montaj-rehberi':('Oto yıkama pervanesi montaj rehberi','Kabin ölçüsü, taşıyıcı yüzey, kol hareket alanı ve hortum hattı: oto yıkama pervanesi montajı öncesinde hazırlanacak saha bilgileri.','Kurulum ve uyum'),
'oto-yikama-pervanesi-nedir':('Oto yıkama pervanesi nedir, nasıl çalışır?','Oto yıkama pervanesi, hortumu yukarıdan taşıyan döner bir kol sistemidir. Çalışma mantığını, kullanım alanlarını ve model türlerini öğrenin.','Seçim ve bütçe'),
'oto-yikama-pervanesi-rulman-arizasi':('Pervane rulman arızasının belirtileri','Dönüş sertliği, metalik ses ve boşluk rulman kontrolü gerektirebilir. Benzer belirtilerin döner rekor veya bağlantılardan da gelebileceğini unutmayın.','Bakım ve arıza'),
'oto-yikama-pervanesi-ses-yapiyor':('Oto yıkama pervanesi neden ses yapar?','Gıcırtı, vuruntu ve basınç altında artan ses aynı nedenden kaynaklanmayabilir. Sesin yerini ve oluştuğu koşulları güvenli biçimde kaydedin.','Bakım ve arıza'),
'oto-yikama-pervanesi-yaglama-noktalari':('Pervane yağlama: gres ve bakım periyodu','Her rulman veya döner rekor yeniden yağlanmaz. Yağlama noktası, gres türü ve miktarı için modele ait üretici talimatını esas alın.','Bakım ve arıza'),
'self-servis-oto-yikama-istasyonu-ekipman-listesi':('Self servis oto yıkama ekipman listesi','Kabin, pervane, hortum, basınç hattı ve drenajı birlikte planlayın. Bu ekipman listesi ön hazırlık içindir; projeye özel keşif yerine geçmez.','Kurulum ve uyum'),
'tir-yikama-istasyonu-ekipmanlari':('Tır yıkama istasyonu ekipmanları','Ağır vasıta erişimi, teleskopik pervane, basınç hattı ve saha altyapısını birlikte değerlendirin. Sabit güç veya basınç ezberleriyle ürün seçmeyin.','Kurulum ve uyum')}
SAFETY='<aside class="notice"><strong>Önce güvenlik.</strong> Bakım veya elle kontrol öncesi enerji ve basıncı üreticinin güvenli durdurma prosedürüne göre izole edin, hattaki artık basıncı boşaltın. Kaçak, gevşeme, çatlak, donma veya takılma varsa kullanımı durdurun. Basınçlı bağlantıyı gevşetmeyin; kaçak yerini elle aramayın. Basınçlı test, söküm ve ayarlar yetkin teknik personel tarafından yapılmalıdır. Bu genel rehber, modelin kullanım ve servis talimatının yerine geçmez.</aside>'
CUSTOM={
'oto-yikama-pervanesi-balans-ayari':'''<p>Oto yıkama pervanesi, hortumun hareketiyle yönlenen bir taşıyıcı koldur. Kolun sallanmasını veya belirli açıda takılmasını motorlu bir fanın dinamik balans problemi gibi ele almak doğru değildir. Önce bağlantı, hizalama ve hortum yükü incelenmelidir.</p>
<h2>Titreşim ile mekanik boşluğu ayırın</h2><p>Kol yalnızca belli bir yönde zorlanıyorsa hortum rotası veya dış temas etkili olabilir. Sabitleme noktasında hareket görülüyorsa taşıyıcı bağlantılar kontrol edilmelidir. Mil çevresindeki oynama ise ölçüm gerektirir. Bu belirtiler tek başına kesin arıza teşhisi değildir.</p>
<h2>Servise iletilecek gözlemler</h2><ul><li>Sorun hangi kabinde ve kolun hangi konumunda görülüyor?</li><li>Hortumda burulma, gereksiz gerginlik veya duvar teması var mı?</li><li>Ses, kaçak veya görünür deformasyon eşlik ediyor mu?</li><li>Sorun montajdan beri mi var, sonradan mı başladı?</li></ul>
<h2>Neyi kendi başınıza değiştirmemelisiniz?</h2><p>Kola karşı ağırlık eklemeyin, kolu eğmeyin, delmeyin veya bağlantıları rastgele sıkmayın. Bu müdahaleler yük dağılımını ve emniyet yapısını değiştirebilir. Ankraj ve bağlantı torkları, taşıyıcı yüzey ve ürün için tanımlanan değerlere göre teknik personelce doğrulanır.</p>
<h2>Teknik kontrol sırası</h2><ol><li>Taşıyıcı yüzey ve bağlantı bütünlüğü değerlendirilir.</li><li>Hortum rotası ile kolun serbest hareket alanı kontrol edilir.</li><li>Mil, yatak ve döner rekor bulguları birbirinden ayrılır.</li><li>Üretici toleranslarıyla ölçüm yapılır ve bakım kararı kaydedilir.</li></ol>
<h2>İlgili rehberler</h2><p><a href="/blog/oto-yikama-pervanesi-mil-boslugu-olcumu/">Mil boşluğu kontrolü</a> ve <a href="/blog/oto-yikama-pervanesi-rulman-arizasi/">rulman arızası belirtileri</a> değerlendirmeyi tamamlar.</p>''',
'oto-yikama-pervanesi-kisin-donma-sorunu':'''<p>Gece boyunca hat içinde kalan su donduğunda hortum, döner rekor ve bağlantılar zarar görebilir. Sabah görülen sert dönüşün nedenini yalnızca soğuk hava olarak kabul etmeyin; hasarlı bir bağlantı veya mekanik sıkışma da aynı belirtiyi verebilir.</p>
<h2>Donma şüphesinde ilk yapılacaklar</h2><ol><li>Kabini kullanıma kapatın; enerji ve basıncı güvenli şekilde izole edin.</li><li>Kol veya hortumu zorlamayın. Donmuş hatta düşük basınç dahil basınç uygulamayın.</li><li>Gözle görülen buz, çatlak, şişme veya kaçak noktalarını uzaktan kaydedin.</li><li>Üreticinin don çözme prosedürü ve teknik servis yönlendirmesini izleyin.</li></ol>
<h2>Isıtma veya basınçla açmak neden uygun değil?</h2><p>Açık alev, kaynar su veya kontrolsüz ısı uygulaması conta, hortum ve bağlantıları etkileyebilir. Akış yolunun tamamen açık olduğu ve parçaların sağlamlığı doğrulanmadan sistemi çalıştırmayın. Donmuş hatta basınç vererek tıkanıklığı açmaya çalışmayın.</p>
<h2>Yeniden devreye alma</h2><p>Don çözüldükten sonra parçaların hasarsız olduğu ve hattın açık olduğu yetkin teknik personel tarafından doğrulanmalıdır. Sızdırmazlık ve işlev testleri üreticinin devreye alma prosedürüne göre yapılır. Kaçak veya takılma devam ediyorsa kullanıma dönülmez.</p>
<h2>Kış öncesi hazırlık</h2><ul><li>Üreticinin hat boşaltma ve don koruma prosedürünü vardiya planına ekleyin.</li><li>Açık hava koşulları, rüzgâr alan bağlantılar ve su birikme noktalarını değerlendirin.</li><li>Hortum ve rekorları modelin çalışma sıcaklığı sınırlarına göre seçin.</li><li>Üretici onayı olmadan hatta antifriz veya başka kimyasal eklemeyin.</li><li>Donma görülen tarih, kabin ve parça bilgisini bakım kaydına işleyin.</li></ul>
<h2>Destek için hazırlanacak bilgiler</h2><p>Ürün modeli, ortam koşulları, duruş süresi ve güvenli mesafeden çekilmiş bağlantı fotoğrafı teşhise yardımcı olur. <a href="/contact/">Beta Makine ile görüşün</a> veya <a href="/blog/oto-yikama-pervanesi-bakimi/">bakım planını inceleyin</a>.</p>''',
'oto-yikama-pervanesi-yaglama-noktalari':'''<p>Yağlama ihtiyacı modelin yatak ve sızdırmazlık tasarımına bağlıdır. Bazı kapalı rulmanlar ve döner bağlantılar yeniden yağlama için tasarlanmamıştır. Ses yapan her noktaya gres uygulamak sorunu çözmez ve kir birikimini artırabilir.</p>
<h2>Yağlama noktası nasıl belirlenir?</h2><p>Önce ürünü ve parça tipini tanımlayın. Üreticinin servis talimatında yağlama noktası, gres türü ve miktarı açıkça belirtilmiyorsa uygulama yapmadan teknik bilgi isteyin. Keçe çevresine, akışkan hattına veya kapalı yatağa gelişigüzel yağ uygulamayın.</p>
<h2>Gres seçerken hangi bilgiler gerekir?</h2><ul><li>Parçanın yeniden yağlamaya uygunluğu.</li><li>Üreticinin belirttiği yağlayıcı türü ve miktarı.</li><li>Çalışma sıcaklığı, su teması ve kimyasal ortam.</li><li>Keçe ve yatak malzemesiyle uyumluluk.</li><li>Mevcut yağlayıcıyla karışabilirlik bilgisi.</li></ul><p>Yalnızca “suya dayanıklı” ifadesi doğru gres seçimi için yeterli değildir. Birbirinden farklı yağlayıcıları üretici onayı olmadan karıştırmayın.</p>
<h2>Kontrol sıklığı ile yağlama sıklığı aynı değildir</h2><p>Yoğun kullanılan bir kabinde daha sık görsel kontrol yapılması, her kontrolde gres eklenmesi gerektiği anlamına gelmez. Sabit haftalık veya aylık yağlama reçetesi yerine modele ait servis aralığı ve saha koşulları esas alınmalıdır.</p>
<h2>Yağlamadan önce mekanik sorunu dışlayın</h2><p>Boşluk, çatlak, kaçak veya belirgin takılma varsa işlemi durdurun. Rulman aşınması, eksen hatası ve yanlış hortum rotası yağ eklenerek giderilmez. Teknik servise ürün modeli, sesin oluştuğu konum ve son bakım bilgisini iletin.</p>
<h2>Bakım kaydına neler yazılır?</h2><p>Tarih, ürün/kabin, gözlem, üreticinin onayladığı uygulama, kullanılan malzeme ve işlemi yapan personel kaydedilmelidir. <a href="/blog/oto-yikama-pervanesi-bakimi/">Genel bakım rehberi</a> ve <a href="/blog/oto-yikama-pervanesi-rulman-arizasi/">rulman belirtileri</a> bu kaydı tamamlar.</p>''',
'tir-yikama-istasyonu-ekipmanlari':'''<p>Tır, kamyon ve otobüs yıkama alanlarında araç yüksekliği ve uzunluğu, hortum erişimi ve güvenli dolaşım alanı birlikte değerlendirilir. Tek bir basınç, motor gücü veya tank kapasitesi bütün işletmeler için doğru değildir.</p>
<h2>Teleskopik tır yıkama pervanesi</h2><p>Beta Makine <a href="/urunler/tir-yikama-pervanesi/">tır yıkama pervanesi</a> kapalı konumda 1,5 metre, açık konumda 3 metre kol uzunluğuna sahiptir. Açılır kapanır yapı ve kopma emniyeti ürünün temel özellikleridir. Montaj yüksekliği ve erişim alanı, en büyük aracın ölçüleriyle birlikte doğrulanmalıdır.</p>
<h2>Basınç hattı ve yıkama ekipmanı</h2><p>Pompa seçimi yalnızca elektrik beslemesine bakılarak yapılmaz. Debi, çalışma basıncı, görev süresi, tabanca/nozül ve eşzamanlı çalışan hat sayısı birlikte değerlendirilir. Hortum ve rekorun izin verilen çalışma değerleri sistemle uyumlu olmalıdır.</p>
<h2>Köpük ve diğer yardımcı sistemler</h2><p>Köpük hattı, dozaj ünitesi ve gerekiyorsa kompresör kullanılan uygulama sistemine göre seçilir. Tank veya kompresör hacmi tek başına performans göstergesi değildir. İç temizlik, vakum ve kurutma ekipmanı ise sunulacak hizmete bağlıdır.</p>
<h2>Saha planı kontrol listesi</h2><ul><li>En büyük aracın yüksekliği, boyu ve dönüş alanı.</li><li>Taşıyıcı yüzeyin uygunluğu ve montaj bağlantıları.</li><li>Kolun, hortumun ve tabancanın tam hareket açıklığı.</li><li>Pompa, hortum, rekor ve tabancanın basınç/sıcaklık uyumu.</li><li>Su tahliyesi, elektrik altyapısı, güvenli erişim ve acil durdurma.</li><li>Bakım için erişilebilen bağlantı noktaları.</li></ul>
<h2>Tedarik kapsamını ayırın</h2><p>Beta Makine kataloğu pervane ve döner bağlantı parçalarını kapsar. Pompa, kompresör, kimyasal veya komple istasyon altyapısı bu ürünlerle aynı tedarik kapsamı olarak varsayılmamalıdır. Kurulum projesini yetkin ekiplerle planlayın.</p><p><a href="/self-servis-oto-yikama-pervanesi/">Teklif öncesi saha bilgileri</a> ve <a href="/blog/oto-yikama-pervanesi-basinc-hortum-uyumu/">basınç-hortum uyumu rehberi</a> ile devam edebilirsiniz.</p>'''}

def remove_section(h):
 for n in list(h.next_siblings):
  if getattr(n,'name',None)=='h2':break
  n.extract()
 h.decompose()

def prepare_article(a):
 slug=a['route'].split('/')[-2]
 name,desc,cat=NOTES[slug]
 a.update(name=name,description=desc,category=cat,title=name+' | Beta Makine')
 s=BeautifulSoup(CUSTOM.get(slug,a['body']),'html.parser')
 if slug not in CUSTOM:
  for h in list(s.select('h2')):
   if any(t in h.get_text() for t in ['İçerik Fikirleri','AI İçin','Boom Pervane Fiyatları']):remove_section(h)
  first=s.find('p')
  if first and any(t in first.get_text() for t in ['Google','aramas','sorgu','en çok aranan']):first.string=desc
  for text in list(s.find_all(string=True)):
   new=str(text)
   for old,replacement in {'15+ yıl boyunca sorunsuz kullanım sağlanır.':'uygun kullanım ve bakım koşullarında dayanıklılık hedeflenir.','Garanti kapsamında ücretsiz servis':'Garanti ve servis kapsamının yazılı teklifte doğrulanması','tam güvenlik sağlanmıştır.':'emniyetli kullanım hedeflenir; montaj ve kullanım talimatları ayrıca uygulanmalıdır.','Tüm profesyonel yıkama ekipmanlarıyla uyumlu olmalıdır':'Mevcut hortum, basınç ve bağlantı standardıyla uyumu doğrulanmalıdır','kullanım yoğunluğunu azaltıp teknik servis planlamasını ertelemeyin':'kullanımı durdurup teknik servisle görüşün','Gerekli durumlarda uygun antifriz kullanımını değerlendirin':'Yalnızca üreticinin açıkça onayladığı don koruma prosedürünü uygulayın','gerekli durumlarda uygun antifriz prosedürü uygulanmalı':'üreticinin onayladığı don koruma prosedürü uygulanmalı','yağ değişimi ve aşınmış parçaların yenilenmesi':'modele uygun bakım ve aşınmış parçaların yenilenmesi','5 Dakikalık Sahada Hızlı Teşhis':'Sahada Ön Kontrol','minimum standardı oluşturur':'örnek bir kontrol çerçevesi sunar; model talimatı önceliklidir',"Checklist'i":'kontrol listesi','Kurulum Sonrası KPI Takibi':'Kurulum sonrası işletme takibi','döner rekor güvenlik seviyesi':'döner rekor seçeneği','en yüksek basınç altında':'ürünün izin verilen çalışma basıncında'}.items():new=new.replace(old,replacement)
   if new!=str(text):text.replace_with(new)
 a['body']=(SAFETY if cat!='Seçim ve bütçe' else '')+str(s)
 if slug in ['oto-yikama-pervanesi-bakimi','oto-yikama-pervanesi-mil-boslugu-olcumu','oto-yikama-pervanesi-rulman-arizasi','oto-yikama-pervanesi-ses-yapiyor']:
  a['body']=a['body'].replace('</aside>','</aside><p class="notice">Periyotlar örnek planlama aralıklarıdır; yağlama veya parça değişimi zorunluluğu olarak okunmamalıdır. Ölçüm sınırları ve bakım aralıkları modelin üretici talimatıyla doğrulanır. Gözlemsel belirtiler kesin arıza teşhisi değildir.</p>',1)
 if slug=='oto-yikama-pervanesi-mil-boslugu-olcumu':
  a['body']=a['body'].replace('<h2>4) Bulgular','<p><strong>Ölçüm sınırı:</strong> Bu rehberde modele ait sayısal boşluk toleransı verilmez. Elle hissedilen oynama hassas ölçüm değildir; kabul veya red kararı üretici toleransıyla yapılır.</p><h2>4) Bulgular')
